name: juicy_spot
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  get: 4.6.1
  timelines: ^0.1.0
  flutter_calendar_carousel: ^2.1.0
  otp_text_field: ^1.1.2
  search_choices: ^2.0.3
  get_storage: ^2.0.3
  dio: ^4.0.4
  connectivity: ^3.0.6
  intl: ^0.17.0
  flutter_local_notifications: ^9.4.0
  timezone: ^0.8.0
  share_plus: ^4.0.4
  in_app_review: ^2.0.4
  url_launcher: ^6.1.0
#  advance_notification: ^1.0.6
  fluttertoast: any
  alice: ^0.2.5
  image_picker: ^0.8.5
  shimmer: ^2.0.0
  cached_network_image: ^3.2.0
  google_fonts: ^3.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons:
  flutter_native_splash:
  change_app_package_name: ^1.0.0 #flutter pub run change_app_package_name:main com.new.package.name

#flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/js_logo.png"

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/svg/
    - assets/images/
